### ISSUE TITLE
LCP2000 Flash Utility Won't Run on Windows 10

### ISSUE THREAD

**Issue by tictag** [UnifiedEngineering/T-962-improvements#102]
LPC2000 Flash ISP Utility v2.2.3 installs fine but reports an error when running on Windows 10 (Anniversary Update). Comes up with a missing file error.

The fix is to, once installed, edit the properties for the shortcut (Launch LPC210x_ISP.exe) and change the compatibility settings to Windows Vista SP2. Works fine after that :)

![2016-11-29_20-05-52](https://cloud.githubusercontent.com/assets/12136834/20726889/4fdbb4e4-b66f-11e6-9ca9-21f0f3869467.png)

**Comment by xnk** [comment]
That's great that the old LPC2k flash util still works, thanks for documenting the workaround!
