### ISSUE TITLE
Earthing Issues with the oven

### ISSUE THREAD

**Issue by DocAlex** [UnifiedEngineering/T-962-improvements#109]
Hi

First of all: Thank you all for providing the new software for the oven. All went fine. The first test is missing. 

I don't know it this is the right place since here it's all about software but I thought it might be interesting.

It's widely known that the oven has an earthing problem since the paint is isolating the earth connector. But the problem is larger:

1. The transformer is isolated as well though the screws are touchable from the outside are connected to the transformer at the inside. A failure of the transformer could lead to a short to ground which then would lead to a screw being connectet to high voltage. 

2. The same issue is for the top cover again its isolated by the paint here it helps to remove the paint with a piloted counterbore and adding some toothed washers. which btw could be a solution for the transformer as well.

3. Some people recommend to remove the paind below the original earth point for proper connection.

The problem with this approach is that the other side of the screw is paced on the plastic mains connector. In case this breaks the earth is no longer connected. My approach is to drill a new hole and use a seperate screw for the earth point. When doing this one can replace the weak earth wire by something stronger (1,5mm^2). Pls be aware that the fuse does not help if the wrong mains wire causes the problem. 

4. The fangrid of the small fan is isolated aswell. This might be acceptable. The above approach wold work aswell. 

I attached some pics for clarification.

Best regards

Alexander 

![img_0381](https://cloud.githubusercontent.com/assets/24655926/22861117/47b03ad8-f111-11e6-9fd5-e19f99302598.JPG)
![img_0385](https://cloud.githubusercontent.com/assets/24655926/22861116/47b00568-f111-11e6-9f92-6307ac4f3dc3.JPG)

**Comment by xnk** [comment]
This is definitely something that would be a good addition to the Wiki, the info may get lost here among the issues.
