### ISSUE TITLE
Calibration 

### ISSUE THREAD

**Issue by SouthernAtHeart** [UnifiedEngineering/T-962-improvements#111]
![img_2167](https://cloud.githubusercontent.com/assets/1664799/24673087/128c8152-1945-11e7-9d17-c49f8367c6f0.JPG)

Is there a way to calibrate the PID control of it? In this photo you can see it's not quite where it should be when it's warming up. 
It's not bad and is very usable. I just wondered if it could be improved.

**Comment by frippe75** [comment]
![20170408_120540](https://cloud.githubusercontent.com/assets/7848204/24828020/fbd66a28-1c54-11e7-96d8-b4f6d5b0f7c9.jpg)

Flashed latest 0.5.1 firmware and installed the coldjunction sensor mod using ds18B20.
Not really sure hot to use setup to try to adjust/calibrate from here. It got too hot using the original firmware now it's the opposite.

**Comment by xnk** [comment]
Lag is to be expected due to the thermal mass. The oven needs to be warmed up by running a dummy cycle or two before reflow. Not reaching peak temperature may be a result of running the main fan slightly too fast.

**Comment by SouthernAtHeart** [comment]
Thanks, I’ll try lowering the fan speed. And running a dummy cycle
