### ISSUE TITLE
Any stencil file available for the TC-IF PCB?

### ISSUE THREAD

**Issue by Houseman74** [UnifiedEngineering/T-962-improvements#116]
Hi. I have bought by osh park the PCB of 1-wire for external thermocouple expansion.
Anyone knows how to get a stencil for it?
I am afraid doing some mess with the small pads of the IC. Best regards and thanks.
Steve

**Comment by GitLang** [comment]
The stencil was an option when you ordered - I think!. I definitely got my stencil from OSH.

**Comment by jake-b** [comment]
I ordered mine from oshstencils.com

**Comment by Houseman74** [comment]
Nope. It was not an option. Otherwise I would have ordered it.

**Comment by Houseman74** [comment]
Thanks Jake. What kind of files do tou have used? Or is it a repository alrrsdy there. Thanks again

**Comment by jake-b** [comment]
I believe the OshPark page where you can purchase the PCB also lets you download the design files as a zip file.  Then upload to OshStencils

**Comment by Houseman74** [comment]
Thanks alot pal
