### ISSUE TITLE
Dallas 18D20 for cold junction mod

### ISSUE THREAD

**Issue by revilor** [UnifiedEngineering/T-962-improvements#118]
I would like to share my experience with the Dallas 18D20 sensor available from lots of sellers e.g. on Amazon. You might think 18D20 is 18D20, just as I did. But that's not the case: the Dallas 18D20 does not provide the 1-wire mode the Maxim 18D20 does. Therefore the cold-junction mod as described in the Wiki does not work with the Dallas. Fortunately the Dallas type can be used anyway. You just have to run the sensor with external supply voltage. One easy spot to get a 3.3V supply for the senosr is in front of the ISP header. There are two tracks on the PCB where the outer one is GND and the inner one is +3.3V. 

![_d8e6616](https://user-images.githubusercontent.com/8861480/33187767-76430354-d094-11e7-8700-17c9cb1f7565.jpg)

The pins of the Dallas sensor are GND - Data - VCC from left to right when looking onto the flat side with the label.

![_d8e6625](https://user-images.githubusercontent.com/8861480/33187769-7679e5d6-d094-11e7-8eb3-34e2cd05337a.jpg)

So the cold-junction mod using the Dallas 18D20 goes as follows:

- remove a bit of the green solder mask to free the 3.3V copper track in front of the ISP header and put a bit of solder there
- solder a piece of wire to the VCC pin of the sensor
- solder a piece of wire to the DATA pin, same as in the original mod
- solder the GND pin of the sensor to ground on the PCB, same place as in the original mod
- add the 4k7 resistor - a regular non-SMD type also works, by the way - and connect the DATA wire as described in the original mod
- solder the sensor's VCC wire to the spot prepared in front of the ISP header
- you are done!

In the end everthing should look similar to this:

![_d8e6624](https://user-images.githubusercontent.com/8861480/33187768-765cbca4-d094-11e7-9eff-1d6f163cb1f6.jpg)

**Comment by revilor** [comment]
I created a wiki page https://github.com/UnifiedEngineering/T-962-improvements/wiki/Dallas-18D20-for-cold-junction-mod which probably is a better fit for this content. So this issue should be closed or deleted.

**Comment by xnk** [comment]
Closing as the wiki was populated with the info
