### ISSUE TITLE
Thermocouple calibration

### ISSUE THREAD

**Issue by waldo3000** [UnifiedEngineering/T-962-improvements#13]
Is it possible that the factory firmware places thermocouple calibration data in the EEPROM?  If so, this could be read and used in the new firmware.

EDIT:  I guess this is not possible since all 256 bytes are used by the custom profiles.  There are some "unused" bytes that are written with values other than 0 and FF, but those are the same for both the t962.h file and my oven's EEPROM so whatever that is, it's probably not calibration.  However, maybe the unused locations could be used for storing calibration data in the new firmware.

**Comment by xnk** [comment]
Issue cleanup
