### ISSUE TITLE
Just another compatible board - How can I donate you?

### ISSUE THREAD

**Issue by Pnoxi** [UnifiedEngineering/T-962-improvements#164]
I made another upgrade for T962. It will be available on [tindie](https://www.tindie.com/products/15262/).

[Hackaday](https://hackaday.io/project/164001-t962t962a-controller-upgrade)

[T962/T962A Controller Upgrade (Part 2) - Installing the controller to T962
](https://youtu.be/GOKtl5OaKDw)

**I can support you from every sold piece. But as? I prefer PayPal.**

![2](https://user-images.githubusercontent.com/44557164/57014051-906e4b00-6c0e-11e9-8330-b67e7f4e5017.jpg)

![5](https://user-images.githubusercontent.com/44557164/57014065-a714a200-6c0e-11e9-9e2c-17406f720d32.jpg)

**Comment by aaronw2** [comment]
Hi,

Just send me a kit and I'll be happy. In my case I am using all 4 
thermocouples so I have two on the board. I like what you did with it. A 
mention in the documentation would also be appreciated. Are you going to have 
two versions, one with the optional thermocouple support?

-Aaronb

**Comment by aaronw2** [comment]
*poke* Any update on this?

**Comment by GitLang** [comment]
What exactly is it that you are waiting for?. You can buy it now straight off --
https://www.tindie.com/products/pnoxi/t-962t-962a-reflow-oven-controller-upgrade/

There is stock of the 2 thrmocouple but 4 thermocouple is sold out.

**Comment by aaronw2** [comment]
On Thursday, September 12, 2019 7:16:14 AM PDT GitLang wrote:
> What exactly is it that you are waiting for?. You can buy it now straight
> off --
> https://www.tindie.com/products/pnoxi/t-962t-962a-reflow-oven-controller-up
> grade/
> 
> There is stock of the 2 thrmocouple but 4 thermocouple is sold out.

You offered to send me a percentage since you used my design and I said that 
instead just send me a couple of boards.

-Aaron

**Comment by GitLang** [comment]
I think you've got the wrong guy!

**Comment by aaronw2** [comment]
Yep, sorry, this was for Pnoxi.

-Aaron

**Comment by Pnoxi** [comment]
> On Thursday, September 12, 2019 7:16:14 AM PDT GitLang wrote: What exactly is it that you are waiting for?. You can buy it now straight off -- https://www.tindie.com/products/pnoxi/t-962t-962a-reflow-oven-controller-up grade/ There is stock of the 2 thrmocouple but 4 thermocouple is sold out.
> You offered to send me a percentage since you used my design and I said that instead just send > -Aaron

**Comment by Pnoxi** [comment]
> You offered to send me a percentage since you used my design and I said that instead just send me a couple of boards.
> -Aaron

Hi, this donate question belonged to the original author of UnifiedEngineering. Not for you aaronw2.
I didn't use your design to develop my board. The development of my board began in 2017.
So I don't see why I should send you one piece for free... :astonished: 
![Snímka obrazovky z 2019-09-15 08-31-54](https://user-images.githubusercontent.com/44557164/64917710-68355200-d793-11e9-88ac-80ce6a306575.png)
