### ISSUE TITLE
IR lamps Issue

### ISSUE THREAD

**Issue by Marora6939** [UnifiedEngineering/T-962-improvements#198]
Hi 
I am working on T-962C IR oven machine. I did ground, cold compensation, kapton taping, updated firmware but still some of my IR lamps are not glowing.
I did check the temperature at different points in oven with the help of thermocouple device. So, the issue is the first three lamps are glowing and they are doing their work but the other three are not working.
Can anyone help me please?
Thank you

_Originally posted by @Marora6939 in https://github.com/UnifiedEngineering/T-962-improvements/issues/106#issuecomment-782116908_

**Comment by Marora6939** [comment]
I found a solution

**Comment by xnk** [comment]
What was the issue?
