### ISSUE TITLE
Where is T962 hex file

### ISSUE THREAD

**Issue by southern-boy** [UnifiedEngineering/T-962-improvements#217]
Where is the T962 hex file located?  Or how do I build it?  Wiki points to the releases pages but I have not found the hex file there.  Is it located somewhere else or did I just not see it?

Thank you.

**Comment by baebjr** [comment]
Bit hard to find:
https://github.com/UnifiedEngineering/T-962-improvements/releases

**Comment by southern-boy** [comment]
Yes baebjr that is the link I posted.  What I did not know is that you have to EXPAND ASSETS to find the hex file.  That was not obvious to me.
