### ISSUE TITLE
AS-5001 compatibility

### ISSUE THREAD

**Issue by xnk** [UnifiedEngineering/T-962-improvements#28]
I wonder how similar the SMTmax AS-5001 and the T-962 ovens are hardware wise. They certainly look very similar but the UI differs a lot. Any AS-5001 users that has disassembled their ovens that are reading this by any chance?

http://www.smtmax.com/detail.php?id=42

**Comment by xnk** [comment]
Seems like the Qinsi QS-5100 may very well be the same or very similar hardware as well. I wonder how they deal with cold junction compensation?

**Comment by bankrasrg** [comment]
According to [this teardown video of the Qinsi QS-5100](http://www.dailymotion.com/video/x36p5uj), the cold-junction compensation is implemented using a MAX6675. Up to 12-bits resolution and measuring range below the cold-junction temperature is a little better than the T-962A.

In the [October 2008 issue of Elektor magazine](https://www.elektor.com/pdf-download-uk-10-2008) a reflow oven with very similar interface has been presented. They probably come with any brand you like.

**Comment by xnk** [comment]
Video confirms Atmel MCU, definitely not compatible :)
