### ISSUE TITLE
LCD issue

### ISSUE THREAD

**Issue by jieter** [UnifiedEngineering/T-962-improvements#36]
I've identified the problem with the LCD being off:
![2015-01-01-193149_908x670_scrot](https://cloud.githubusercontent.com/assets/1470389/5592967/e58690f8-91ec-11e4-900b-0b7184cb1a96.png)

Don't know what exactly happened... 

Package marking is LTKF which seems to be a [LT1617 micropower inverting DC/DC converter] (http://cds.linear.com/docs/en/datasheet/16171f.pdf) Will try to replace that part. Or find a compatible LCD module, which might be hard...

**Comment by xnk** [comment]
Oops! Did one of the pins break off, as in no easy way to re-solder the one you have? That's got to be the negative bias regulator for the LC assembly. Probably easiest to replace the regulator than to replace the display.

**Comment by jieter** [comment]
I tried resoldering, but it was hurt badly. One pin broke of, I even tried resoldering that pin by grinding off a piece of the case. Did not help.
Will order a replacement part today.

**Comment by xnk** [comment]
:( At least it's a trivial replacement procedure with one of those packages.

**Comment by jieter** [comment]
yes, should be a breeze. Hopefully, nothing else is broken.

**Comment by xnk** [comment]
You can always try to feed an external negative voltage from an isolated power supply through a 1k resistor or so to the output of the converter circuit and ramp up from 0 and see when you get decent contrast. I believe this negative voltage only goes out to the external contrast adjustment trimmer and then back in again. That way you can verify that nothing else is broken.

**Comment by jieter** [comment]
Just tried with a 9V battery: provides just enough contrast to see it...

**Comment by jieter** [comment]
Alive again ;)

![img-20150109-wa0006](https://cloud.githubusercontent.com/assets/1470389/5681003/6389a24c-9814-11e4-9d60-8b51671502ab.jpg)

**Comment by xnk** [comment]
Congratulations!!!
