### ISSUE TITLE
Reset after flashing firmware

### ISSUE THREAD

**Issue by jieter** [UnifiedEngineering/T-962-improvements#52]
Is it possible to reset the uC automagically after flashing the new software from the bootloader?

**Comment by xnk** [comment]
As in jumping to the code from ISP mode? The NXP tool has a "jump to code" command that I used for initial RAM load/execute, that _should_ work for flashed firmware too.

**Comment by jieter** [comment]
I did quite some flashing of new code yesterday, and it's quite annoying to have to turn of the oven to reset it after the upload is completed. Maybe I just have to figure out the DTR/RTS for reset/ISP...

**Comment by xnk** [comment]
Aha, right! I have both the ISP and RESET pins hooked up. I haven't experimented with the DTR and RTS, but there appears to be a standard how to hook it up. Seems like most terminal programs isn't working properly when hooking dtr/rts up though (forces reset when opening the serial port). Not sure where that was mentioned though..

**Comment by xnk** [comment]
Issue cleanup
