### ISSUE TITLE
X1 and X2 temperatures neglected for actual temp display + findings

### ISSUE THREAD

**Issue by electronicamystica** [UnifiedEngineering/T-962-improvements#60]
I noticed X1 and X2 (from the MAX31850K interface) don't seem to be used for calculating the actual temperature shown in baking mode (shows 101.5C instead of 106C:

![x1 not in actual temp](https://cloud.githubusercontent.com/assets/11185672/6393697/98eb87ec-bdcc-11e4-973a-6c5afaeb12b7.jpg)

I can't say if X1/X2 are used when baking.
The X1/X2  temperature however seems to be taken into account when reflowing, here some tests I did. I ran every profile configuration several times with empty oven and minimum fan=12 and the graphs for each configuration are always similar:

L+R only used (L+R reversed in this picture) :
![l and r swapped - fan 12 -nc-31_low-temp_lf](https://cloud.githubusercontent.com/assets/11185672/6393763/394a0ca4-bdcd-11e4-9b19-5d3ed61256e1.png)

X1 next to L:
![x1 next to l - fan 12 - nc-31_low-temp_lf](https://cloud.githubusercontent.com/assets/11185672/6393770/40a41a4e-bdcd-11e4-9807-c5a1a9e6064a.png)

X1 between L+R but closer to the pcbs:
![x1 between l and r - fan 12 -nc-31_low-temp_lf](https://cloud.githubusercontent.com/assets/11185672/6393771/43151620-bdcd-11e4-89e5-338b5500e77f.png)

X1 next to R:
![x1 next to r - fan 12 -nc-31_low-temp_lf](https://cloud.githubusercontent.com/assets/11185672/6393775/454dc450-bdcd-11e4-9f58-8b269e7bc3c9.png)

Does anyone have similar differences between L+R when the fan is on?
I just measured the distance from the tip of the sensors to the tray walls and they differ by 2cm with the right sensor being closer to the wall which would make sense as it takes longer to cool down (always has higher temperature when fan is on).
This could mean that the sensor placement is quite critical and I should readjust them. I will do some tests on replacing them now.

**Comment by wysiwywg** [comment]
After repositioning R symmetrical to L it looks the same I would say:
![x1 between l and r 2nd -fan 12 -nc-31_low-temp_lf](https://cloud.githubusercontent.com/assets/11185672/6395004/ce6b8878-bdd5-11e4-9257-c5262ff1d649.png)
That's good, so the difference before doesn't matter.

Then I looked at the csv files and the actual temperature shown there also is only calculated from L+R.
The temperature curve plot with X1 mounted 1cm above a pcb in the middle of the tray looks promising:
![x1 middle pcb](https://cloud.githubusercontent.com/assets/11185672/6395803/dc60fdc8-bdda-11e4-8e0d-9ea297fcba77.png)

**Comment by xnk** [comment]
Very true, X1 and X2 are for measurement/validation only in the current firmware. If you take a look at the MAXTEMPOVERRIDE define here https://github.com/UnifiedEngineering/T-962-improvements/blob/master/src/reflow.c#L36-44 then you might get closer to the result you're after. I haven't come up with a good way of configuring this without recompiling yet. There are quite a few scenarios to take care of, unplugged external sensors being one, external sensors left outside the oven being another. Any ideas?

It seems that a lot of these ovens have a cooler left side, especially when running the fan, and that temperature difference will clearly prevent proper reflowing. Could the airflow be redirected upwards perhaps?

**Comment by wysiwywg** [comment]
I will try with MAXTEMPOVERRIDE, though I think I will need to set a temperature offset for the whole curve, as it will result in a even lower overall temperature at my current configuration? (if I understood the funtion right). When using the external sensors the TC offset in the setup menu doesn't have any effect. Propably good to change that?
I guess left outside of the oven can be detected very early in the soldering process due to no temperature response? Doesn't the firmware already detect missing sensors?
Toggling sensors
Probably add such test functions with a debug mode you enter starting the oven holding down"S"?

I did a few tests with the 63Sn/37Pb profile measuring X1 at  different corners of the oven (3cm from the tray walls 1cm above surface). Measuring points were like this

1________2
 ____3____
4________5

(1)
![pos1](https://cloud.githubusercontent.com/assets/11185672/6411530/c65f6024-be79-11e4-8510-9a886b532e48.png)
(2)
![pos2](https://cloud.githubusercontent.com/assets/11185672/6411535/d101b2f2-be79-11e4-8629-007f61d5d6aa.png)
(3)
![pos3](https://cloud.githubusercontent.com/assets/11185672/6411540/e1273c92-be79-11e4-829b-36214c7115ad.png)
(4)
![pos4](https://cloud.githubusercontent.com/assets/11185672/6411545/ede9f4ec-be79-11e4-8efe-5b2ae6714f8c.png)
(5)
![pos5](https://cloud.githubusercontent.com/assets/11185672/6411547/f19831f8-be79-11e4-8cae-acc3c32790d4.png)

This correlates to my experience pcbs in the middle reflowing fine, to the right maybe and to the left not. With standard settings that is.  Is Bismuth paste the way to go for sensitive components/reliable reflowing then?
I got really good results with chinese Bi/Sn paste, but don't dare shipping out a hundred Bi/Sn soldered pcbs yet.

**Comment by wysiwywg** [comment]
setting the fan to 0 definitely helps to move all curves a bit up here the curve at pos 5 with fan=0:
![pos5_fan_0](https://cloud.githubusercontent.com/assets/11185672/6412593/34649100-be86-11e4-9efd-688beef3b03c.png)
and pos3 with fan=0:
![pos3_fan_0](https://cloud.githubusercontent.com/assets/11185672/6412596/3ffb1b42-be86-11e4-9d52-f46968b06749.png)

Then I took your idea of redirecting the airflow and installed an 32mmx85mm obstacle at the back of the tray:
![obstacle1 32mmx85mm](https://cloud.githubusercontent.com/assets/11185672/6412787/a17ff1f6-be88-11e4-83b6-8e10b95c11a9.jpg)

pos 5 with fan=12 and obstacle1:
![pos5_fan_12_obstacle1](https://cloud.githubusercontent.com/assets/11185672/6412680/6c64c7b8-be87-11e4-8fa1-1594743707cf.png)
and pos3 with fan=12 and obstacle (tejp went off during reflowing, so sensor is a bit higher:
![pos3_fan_12_obstacle1](https://cloud.githubusercontent.com/assets/11185672/6412730/0f24a05e-be88-11e4-96d8-a95a28e2e3ac.png)
Now that looks promising:-) Good idea you had there!

Having X1 and X2 plotted in serial-control.py would be neat.

**Comment by electronicamystica** [comment]
new test with measuring points placed like this:
A B C
D E F
G H I
first picture always with obstacle, second without.
A
![2015-03-01-103347-4300_63sn_37pb - posa](https://cloud.githubusercontent.com/assets/11185672/6430691/231a3590-c015-11e4-8e06-563d64754f20.png)
![2015-03-01-134452-4300_63sn_37pb-posa](https://cloud.githubusercontent.com/assets/11185672/6430824/7d1f5074-c01b-11e4-8f6c-e35949377958.png)


B
![2015-03-01-105308-4300_63sn_37pb-posb](https://cloud.githubusercontent.com/assets/11185672/6430690/20286b72-c015-11e4-9da0-8ba6d0c60c15.png)
![2015-03-01-132229-4300_63sn_37pb-posb](https://cloud.githubusercontent.com/assets/11185672/6430763/4cfdbaa0-c018-11e4-8225-a356d927ae7d.png)


C
![2015-03-01-110010-4300_63sn_37pb-posc](https://cloud.githubusercontent.com/assets/11185672/6430687/f1d98652-c014-11e4-9b69-bc0535d0e352.png)
![2015-03-01-131510-4300_63sn_37pb-posc](https://cloud.githubusercontent.com/assets/11185672/6430688/fef44f8e-c014-11e4-8f46-26d1326804fe.png)

D
![2015-03-01-111052-4300_63sn_37pb-posd](https://cloud.githubusercontent.com/assets/11185672/6430685/dd11fab0-c014-11e4-946a-0f8c685b9035.png)
![2015-03-01-130610-4300_63sn_37pb-posd](https://cloud.githubusercontent.com/assets/11185672/6430686/e473449e-c014-11e4-9864-368d28ba0602.png)

E
![2015-03-01-111748-4300_63sn_37pb-pose](https://cloud.githubusercontent.com/assets/11185672/6430644/f113d86e-c012-11e4-8bce-6490b198aff0.png)
![2015-03-01-125155-4300_63sn_37pb-pose](https://cloud.githubusercontent.com/assets/11185672/6430646/0697b192-c013-11e4-9b74-9b9fcd47701a.png)

F
![2015-03-01-112642-4300_63sn_37pb-posf](https://cloud.githubusercontent.com/assets/11185672/6430583/9c47fa6a-c010-11e4-803f-73ebb9c9e75e.png)
![2015-03-01-124444-4300_63sn_37pb-posf](https://cloud.githubusercontent.com/assets/11185672/6430584/bf6cb2a6-c010-11e4-9525-ab03e8dfead2.png)

G
![2015-03-01-114333-4300_63sn_37pb-posg](https://cloud.githubusercontent.com/assets/11185672/6430575/507afc68-c010-11e4-97fa-7c698c314779.png)
![2015-03-01-123624-4300_63sn_37pb-posg](https://cloud.githubusercontent.com/assets/11185672/6430576/5ce03ea0-c010-11e4-8a90-25bd68c45c23.png)
H
![2015-03-01-115053-4300_63sn_37pb-posh](https://cloud.githubusercontent.com/assets/11185672/6430572/3d5fcb7c-c010-11e4-981d-8f4cc85ef414.png)
![2015-03-01-122626-4300_63sn_37pb-posh](https://cloud.githubusercontent.com/assets/11185672/6430573/3fc54068-c010-11e4-86d6-9f36c94ec90f.png)
I
![2015-03-01-120119-4300_63sn_37pb posi](https://cloud.githubusercontent.com/assets/11185672/6430567/245b7630-c010-11e4-80ba-0bebd617da61.png)
![2015-03-01-121136-4300_63sn_37pb-posi](https://cloud.githubusercontent.com/assets/11185672/6430570/3200428e-c010-11e4-9681-c98fbd9c3353.png)

I can't discover any deeper wisdom here apart from the simple obstacle not being a solution either and pcb color isn't taken into account either. I usually use black pcbs which should get warmer then green/white ones.
Wenn a preheated oven definitely helps it seems as i did the last set of tests without obstacle shortly after another.

**Comment by xnk** [comment]
Issue cleanup
