### ISSUE TITLE
Schematic missing

### ISSUE THREAD

**Issue by JetForMe** [UnifiedEngineering/T-962-improvements#69]
Leads to a missing dropbox file: https://github.com/UnifiedEngineering/T-962-improvements/wiki/T92A-Controller-Schematics

**Comment by RasmusB** [comment]
Strange, it works for me?

**Comment by JetForMe** [comment]
I tried again, and there it is. Sigh. Sorry.

**Comment by jieter** [comment]
Maybe it's a good plan to move it into the report anyway...
