### ISSUE TITLE
Failed to autobaud. (Operation failed)

### ISSUE THREAD

**Issue by rs98** [UnifiedEngineering/T-962-improvements#78]
Hello,
I'm trying to first-flash my T-962 (purchased in summer 2015). A few moments after I hit Start Button Flash Magic Utility says "Operation Failed. Failed to autobaud. See http://www.flashmagictool.com/autobaud.html". LPC2000 says "Reading of PART ID Failed"
My COM port is OK, connection is done according to schematics you provide. I'm using jumpers to enter bootloader. Apparently LPC2134 is switching into bootloader mode. However flashing with LPC2000  v2.2.3 or Flash Magic v 9.20.3898 failed at the beginning because they cannot communicate with the board.  
However, when I started Terminal in Flash Magic Tools and after manual reset / bootloader entering "?", I'm receiving responses, for example 0xC2B235C28DC38A7AC39A141A6A5A54C2BA2AC3AB. Thus it seems the communication is OK.
Please advice if I'm missing something specific for communicating with LPC2134. 
I'm using Win 7 with SystemBase PCI to Serial Port card.
Best regards,
Rinat

**Comment by RasmusB** [comment]
Have you tried with the settings suggested in the Wiki? There is a suggested baud rate there, so you should not need to autobaud anything. 
https://github.com/UnifiedEngineering/T-962-improvements/wiki/Flashing-the-LPC21xx-controller

**Comment by rs98** [comment]
Of course I followed suggestions in the wiki (including suggested baud rate 57600):
https://github.com/UnifiedEngineering/T-962-improvements/wiki/Flashing-the-LPC21xx-controller
Even so Flash Magic is trying (and failed) to autobaud and LPC2000 says "Cannot communicate with test board". 
I also made a new serial cable and also tried optional DTR and RTS control of RST and ISP pins.
Is there any requirements for waveform / timing of n_RESET and n_ISP pulses?

**Comment by RasmusB** [comment]
No special requirements, once you have entered the bootloader you shouldn't need to touch RESET or ISP before flashing. I just did it with simple push buttons without problems.

**Comment by rs98** [comment]
What was your COM port settings? 
My are (defaults) 57600 bps, 8 data bits, parity: none, 1 stop bit. Flow control: none. I also tried Flow control: Xon/Xoff.

**Comment by sapperdaddy** [comment]
I had the same issue. Turned out I had the Rx and Tx backwards.

**Comment by piyushverma** [comment]
I am using linux ./lpc21isp build/T-962-controller.hex /dev/ttyUSB0 57600 11059 to flash but facing similar problem. 

any Suggestion ?

I have not used LPC21... So I thought to buy sample board and programmer to test first then flash in this.

I believe any USB -> RS232 dongle should do it like pL2303 please suggestion how to fix it

**Comment by rharrison** [comment]
I spent 4 hours trying to flash the oven with flash magic. The solution in the end was to set the baud rate to 14400 and everything worked ok after that.

**Comment by pandaritrl** [comment]
It worked at 2400 baud rate for me.

**Comment by Mavrikant** [comment]
I had the same problem. I used 9600 baudrate. And also removed reset cable after entering bootloader mode because when I hit "Read Device Signature" option, device resets itself and gets out of mode.

**Comment by xnk** [comment]
Issue cleanup
