### ISSUE TITLE
SystemFan_ValidateNV() used in setup.c before definition

### ISSUE THREAD

**Issue by GitLang** [UnifiedEngineering/T-962-improvements#84]
SystemFan_ValidateNV() is called in Setup_setValue() in setup.c. LPCXpresso is making mild complaints

../src/setup.c:60:2: warning: implicit declaration of function 'SystemFan_ValidateNV'

Solution is to add  #include "systemfan.h" to setup.c

**Comment by jieter** [comment]
@GitLang can you open a PR? Maybe @xnk can make someone else member so we can actually maintain this repository.

**Comment by xnk** [comment]
Issue cleanup, code was refactored
