### ISSUE TITLE
1.) PID tuning

### ISSUE THREAD

**Issue by GitLang** [UnifiedEngineering/T-962-improvements#86]
Is it OK to discuss general software and hardware issues here please?. If not, I don't now where else to go. I'll try to get away with 3 subjects and if I fail, just kick me out :)

1) PID tuning. I believe what PID tuning has been done is fixed in firmware, in reflow.c, yes?. If so, this is an are I would like to look at and have some experience over the last 40 years. However I don't yey understand CVS, I've alwys worked just about on my own and not had need for it. Can somebody point me at a beginners guide to CVS/Git please?. If I can achieve something with PID it would be good to give it back.

**Comment by xnk** [comment]
Issues has been used for a lot of different reasons :) For reference: GitHub does have quite a lot of information here https://help.github.com/articles/git-and-github-learning-resources/
