### ISSUE TITLE
2.) MAX31855 in SPI mode

### ISSUE THREAD

**Issue by GitLang** [UnifiedEngineering/T-962-improvements#87]
2) Using MAX31855 in SPI mode. Is there any reason I can't use a standard dual 31855 SPI board for the thermocouples. I thought SPI would be just a matter of finding 4 spare i/o bits and rolling my own SPI code. But I hear things like "There's only one SPI port left and one of it's signals is in use for other things". Why is this a problem?. Move the "other thing" and use the built in SPI or find 4 ports and roll your own. Seems a shame not to be able to use off the shelf hardware when there are so many SPI cards about with this chip and so few I2C. Yes, I've seen the quad I2C board offered by one of us, it looks good. But as other's have said I'm not confident of soldering the 31850 on this machine yet as it's so unstable, and hand soldering it looks out. I have some 31856 chips but they look just as bad and need even more i/o if you use the Fault line etc.

**Comment by xnk** [comment]
There simply are no more spare IOs on the MCU as a lot of them get used up by the LCD interface. A spare pin was found for 1-wire, the external EEPROM already uses I2C. Another spare IO was found to do system fan control, but that's about it.
